---
#
# Playbook to install the ELK stack + Beats
#
- hosts: localhost
  gather_facts: yes

  pre_tasks:
    - name: update apt cache if needed
      become: yes
      apt:
        update_cache=yes
        cache_valid_time=3600

  tasks:
    - name: Install Java Runtime Environment 
      become: yes
      apt:
       name: default-jre
       state: present

  remote_user: ubuntu
  become: yes
  become_user: root
  roles:
  - { role: elasticsearch }
  - { role: kibana }
  - { role: logstash }
  - { role: filebeat }
  - { role: metricbeat }

